// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARalWv6DEOllYMzeEnTfSffM2F52Vplw8',
    appId: '1:240183454171:web:9a6f4ad3b9ab6cc47b1ffe',
    messagingSenderId: '240183454171',
    projectId: 'sales-friend',
    authDomain: 'sales-friend.firebaseapp.com',
    storageBucket: 'sales-friend.firebasestorage.app',
    measurementId: 'G-7T2BLLXCV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdhcSldx5Mt2PvKtc5RfvVHITp2cdL6G8',
    appId: '1:240183454171:android:6ab64b9997b0dda67b1ffe',
    messagingSenderId: '240183454171',
    projectId: 'sales-friend',
    storageBucket: 'sales-friend.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3aG-LZnqyUgnzcOkYDgX098DJHoQHbE4',
    appId: '1:240183454171:ios:0c41bd96af6313d07b1ffe',
    messagingSenderId: '240183454171',
    projectId: 'sales-friend',
    storageBucket: 'sales-friend.firebasestorage.app',
    iosBundleId: 'com.example.salesFriend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3aG-LZnqyUgnzcOkYDgX098DJHoQHbE4',
    appId: '1:240183454171:ios:0c41bd96af6313d07b1ffe',
    messagingSenderId: '240183454171',
    projectId: 'sales-friend',
    storageBucket: 'sales-friend.firebasestorage.app',
    iosBundleId: 'com.example.salesFriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARalWv6DEOllYMzeEnTfSffM2F52Vplw8',
    appId: '1:240183454171:web:e038323ef8eef37e7b1ffe',
    messagingSenderId: '240183454171',
    projectId: 'sales-friend',
    authDomain: 'sales-friend.firebaseapp.com',
    storageBucket: 'sales-friend.firebasestorage.app',
    measurementId: 'G-HTSFMERKB6',
  );
}
